# Cassandra Configuration
spring.cassandra.keyspace-name=your_keyspace
spring.cassandra.contact-points=cassandra
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=demo-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
#spring.kafka.producer.retries=3
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE
#spring.kafka.properties.security.protocol=PLAINTEXT

# Ignite Configuration
ignite.discovery.tcp.remote-addresses=ignite:47500
ignite.local-address=spring-app
ignite.discovery.port=47500
ignite.discovery.port-range=20
ignite.client-mode=false  # Optional: Set to 'true' if this service will be a client in the Ignite cluster

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.org.apache.ignite=DEBUG
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG
logging.level.org.apache.kafka=WARN

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Additional Spring Configuration
spring.application.name=demo-application
spring.main.allow-bean-definition-overriding=true
